# models/staging/raw_customer_data.yml


version: 2
sources:
  - name: raw_customer_data
    database: DEMO_DB
    schema: TEST_SCHEMA
    tables:
      - name: raw_customer_data
      tables:
        - name: raw_sales_data
   


models:
  - name: staging_customer_data
    description: "Staging model for raw customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: email
        description: "Email address of the customer"
      - name: phone_number
        description: "Phone number of the customer"
      - name: registration_date
        description: "Registration date of the customer"
        tests:
          - not_null
    materialized: view
    